/* ═══════════════════════════════════════════════════════════
   {{BRAND}} — exam / series / subject catalog (US English frame)

   First-time setup asks "Which exam are you taking?" → (if the exam has a
   series) which series → which subjects. Each subject's material lives in
   one data/<file>.js. Only a subject with material loads; others show
   "Coming soon." Which subjects are ready is reported by data/ready.js
   (a pipeline artifact) — counts are never hard-coded here.

   CPA candidates sit for each section (REG, FAR, TCP, AUD) on their own schedule (no single fixed test
   date), so date stays null and the learner enters their own test date on
   the Settings screen. When date is null, GB.goal() just falls back to
   today as a placeholder goal — nothing breaks.

   To add CFA Level I — Ethics once its data lands in data/cfa_l1_ethics.js,
   add a subject entry and an EXAMS entry the same way as REG below (3
   choices per question instead of REG's 4 — the app already supports 3-5).
   ═══════════════════════════════════════════════════════════ */
(function () {
  "use strict";
  /* Subjects — key is the data/ filename (letters, digits, underscore). name is the display name. */
  var SUBJECTS = {
    /* BEGIN REG SUBJECTS — generated by tools/build_reg.py, do not hand-edit */
    reg_area1_ethics_procedures: { name: "Area I · Ethics and Federal Tax Procedures", area: "I", weight: 15 },
    reg_area2_business_law: { name: "Area II · Business Law", area: "II", weight: 20 },
    reg_area3_property: { name: "Area III · Property Transactions", area: "III", weight: 10 },
    reg_area4_individuals: { name: "Area IV · Individual Taxation", area: "IV", weight: 27 },
    reg_area5_entities: { name: "Area V · Entity Taxation", area: "V", weight: 28 },
    /* END REG SUBJECTS */
    /* BEGIN FAR SUBJECTS — generated by tools/build_far.py, do not hand-edit */
    far_area1_financial_reporting: { name: "Area I · Financial Reporting", area: "I", weight: 35 },
    far_area2_balance_sheet: { name: "Area II · Select Balance Sheet Accounts", area: "II", weight: 35 },
    far_area3_transactions: { name: "Area III · Select Transactions", area: "III", weight: 30 },
    /* END FAR SUBJECTS */
    /* BEGIN TCP SUBJECTS — generated by tools/build_tcp.py, do not hand-edit */
    tcp_area1_individuals: { name: "Area I · Individuals and Personal Financial Planning", area: "I", weight: 35 },
    tcp_area2_entity_compliance: { name: "Area II · Entity Tax Compliance", area: "II", weight: 35 },
    tcp_area3_entity_planning: { name: "Area III · Entity Tax Planning", area: "III", weight: 15 },
    tcp_area4_property: { name: "Area IV · Property Transactions", area: "IV", weight: 15 },
    /* END TCP SUBJECTS */
    /* BEGIN AUD SUBJECTS — generated by tools/build_aud.py, do not hand-edit */
    aud_area1_ethics_responsibilities: { name: "Area I · Ethics and Professional Responsibilities", area: "I", weight: 20 },
    aud_area2_risk_assessment: { name: "Area II · Risk Assessment and Planned Response", area: "II", weight: 30 },
    aud_area3_evidence: { name: "Area III · Further Procedures and Evidence", area: "III", weight: 35 },
    aud_area4_reporting: { name: "Area IV · Conclusions and Reporting", area: "IV", weight: 15 },
    /* END AUD SUBJECTS */
    cfa_l1_ethics: { name: "Ethical and Professional Standards" }
  };

  /* Exams — an exam with only one series omits the series list. */
  var EXAMS = [
    { id: "cpa", sec: "REG", name: "US CPA — REG (Regulation)", sub: "Terra Prep original questions aligned to the 2026 AICPA Blueprint.",
      date: null, subs: /* BEGIN REG SUBS */["reg_area1_ethics_procedures", "reg_area2_business_law", "reg_area3_property", "reg_area4_individuals", "reg_area5_entities"]/* END REG SUBS */ },
    { id: "cpa_far", sec: "FAR", name: "US CPA — FAR (Financial Accounting and Reporting)", sub: "Terra Prep original questions aligned to the 2026 AICPA Blueprint. Journal entry drill included.",
      date: null, subs: /* BEGIN FAR SUBS */["far_area1_financial_reporting", "far_area2_balance_sheet", "far_area3_transactions"]/* END FAR SUBS */ },
    { id: "cpa_tcp", sec: "TCP", name: "US CPA — TCP (Tax Compliance and Planning)", sub: "Elective discipline. Terra Prep original questions aligned to the 2026 AICPA Blueprint.",
      date: null, subs: /* BEGIN TCP SUBS */["tcp_area1_individuals", "tcp_area2_entity_compliance", "tcp_area3_entity_planning", "tcp_area4_property"]/* END TCP SUBS */ },
    { id: "cpa_aud", sec: "AUD", name: "US CPA — AUD (Auditing and Attestation)", sub: "Core section. Terra Prep original questions aligned to the 2026 AICPA Blueprint.",
      date: null, subs: /* BEGIN AUD SUBS */["aud_area1_ethics_responsibilities", "aud_area2_risk_assessment", "aud_area3_evidence", "aud_area4_reporting"]/* END AUD SUBS */ },
    { id: "cfa1", name: "CFA Level I", sub: "Computer-based testing available year-round — enter your own test date on the Settings screen.",
      date: null, series: [
        { id: "ethics", name: "Ethics", subs: ["cfa_l1_ethics"] } ] }
  ];

  function exam(id) { return EXAMS.filter(function (e) { return e.id === id; })[0] || null; }
  function series(examId, sid) {
    var e = exam(examId); if (!e || !e.series) return null;
    return e.series.filter(function (s) { return s.id === sid; })[0] || null;
  }
  /* The subjects this learner is taking — determined by exam + series */
  function subsOf(examId, sid) {
    var e = exam(examId); if (!e) return [];
    if (!e.series) return e.subs.slice();
    var s = series(examId, sid); return s ? s.subs.slice() : [];
  }
  /* CPA sections (REG, FAR, TCP, AUD): each is its own exam entry, so history, test date and plan are kept apart per section */
  function sections() { return EXAMS.filter(function (e) { return !!e.sec; }); }
  function ready(id) { return !!(window.READY && window.READY[id]); }
  function count(id) { return (window.READY && window.READY[id] && window.READY[id].n) || 0; }

  window.CATALOG = { SUBJECTS: SUBJECTS, EXAMS: EXAMS, exam: exam, sections: sections, series: series, subsOf: subsOf,
                     ready: ready, count: count,
                     name: function (id) { return (SUBJECTS[id] || { name: id }).name; },
                     area: function (id) { return (SUBJECTS[id] || {}).area || ""; },
                     weight: function (id) { return (SUBJECTS[id] || {}).weight || 0; } };
})();
