/* Terra Prep — offline cache (service worker).
   App files and question data are cached on first visit, so practice works without a connection.
   The cache name carries a content hash written by tools/build_reg.py: any change to a shipped file
   changes the hash, the new worker installs in the background and waits, and the page shows
   "A new version is ready" (js/pwa.js). Study history stays in localStorage and is never touched here. */
/* BEGIN PRECACHE — generated by tools/build_reg.py, do not hand-edit */
var VERSION = "853f202096";
var FILES = [
 "cards.html",
 "css/app.css",
 "css/features.css",
 "css/je.css",
 "css/learn.css",
 "css/tacct.css",
 "css/tbs.css",
 "data/aud_area1_ethics_responsibilities.js",
 "data/aud_area2_risk_assessment.js",
 "data/aud_area3_evidence.js",
 "data/aud_area4_reporting.js",
 "data/cards_reg.js",
 "data/cfa_l1_ethics.js",
 "data/far_area1_financial_reporting.js",
 "data/far_area2_balance_sheet.js",
 "data/far_area3_transactions.js",
 "data/je_far.js",
 "data/ready.js",
 "data/reg_area1_ethics_procedures.js",
 "data/reg_area2_business_law.js",
 "data/reg_area3_property.js",
 "data/reg_area4_individuals.js",
 "data/reg_area5_entities.js",
 "data/tbs_far.js",
 "data/tbs_reg.js",
 "data/tcp_area1_individuals.js",
 "data/tcp_area2_entity_compliance.js",
 "data/tcp_area3_entity_planning.js",
 "data/tcp_area4_property.js",
 "drill.html",
 "exam.html",
 "icons/favicon.svg",
 "icons/icon-192.png",
 "icons/icon-512.png",
 "icons/icon-maskable-512.png",
 "index.html",
 "insights.html",
 "je.html",
 "js/boot.js",
 "js/brand.js",
 "js/catalog.js",
 "js/je.js",
 "js/jegrade.js",
 "js/judge.js",
 "js/learn.js",
 "js/pwa.js",
 "js/store.js",
 "js/tacct.js",
 "js/tbs.js",
 "learn.html",
 "manifest.webmanifest",
 "method.html",
 "ox.html",
 "plan.html",
 "settings.html",
 "skilltree.html",
 "start.html",
 "tbs.html"
];
/* END PRECACHE */
var CACHE = "terra-prep-" + VERSION;

self.addEventListener("install", function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) {
    return Promise.all(FILES.map(function (f) { return c.add(new Request(f, { cache: "reload" })); }));
  }));
});

self.addEventListener("activate", function (e) {
  e.waitUntil(caches.keys().then(function (ks) {
    return Promise.all(ks.filter(function (k) { return /^terra-prep-/.test(k) && k !== CACHE; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener("message", function (e) {
  if (e.data === "skipWaiting") self.skipWaiting();
  else if (e.data === "version" && e.source) e.source.postMessage({ version: VERSION });
});

self.addEventListener("fetch", function (e) {
  var req = e.request;
  if (req.method !== "GET") return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  var nav = req.mode === "navigate";
  var target = req;
  if (nav && /\/$/.test(url.pathname)) target = new Request(new URL("index.html", url).href);
  e.respondWith(caches.open(CACHE).then(function (c) {
    return c.match(target, { ignoreSearch: true }).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (res) {
        if (res && res.ok && res.type === "basic") c.put(req, res.clone());
        return res;
      }).catch(function () {
        return nav ? c.match("index.html") : Response.error();
      });
    });
  }));
});
