# -*- coding: utf-8 -*-
"""Sync TBS sources from cloud-work and build data/tbs_reg.js.

    py tools/build_tbs.py            fetch cloud-work branch, copy sources to tools/src/TBS, write data/tbs_reg.js
    py tools/build_tbs.py --no-fetch skip `git fetch` (use the already fetched origin ref)

Sources (branch claude/terra-prep-becker, jobs/terra-prep-becker/...): TBS_SPEC.md, 원천/REG/tbs_reg.json,
tbs_lib.py, tbs_items_{1,3,4,5}.py, tbs_계산검산.py, tbs_문제지_검산용.json.
The browser file carries the raw templates (params / vary / guards / derived / cell formulas) so that
js/tbs.js can rebuild the original and any number variant. Answers ship with the data (static site; see TBS_SPEC 4).
"""
import json, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CW = os.environ.get("CLOUD_WORK", r"C:\Users\서문여고\테라러닝_2컴\작업\cloud-work")
REF = "origin/claude/terra-prep-becker"
BASE = "jobs/terra-prep-becker/"
SRC = os.path.join(ROOT, "tools", "src", "TBS")
FILES = [("TBS_SPEC.md", "TBS_SPEC.md")] + [("원천/REG/" + n, n) for n in (
    "tbs_reg.json", "tbs_lib.py", "tbs_items_1.py", "tbs_items_3.py", "tbs_items_4.py", "tbs_items_5.py",
    "tbs_계산검산.py", "tbs_문제지_검산용.json")]
ENV = dict(os.environ, GIT_TERMINAL_PROMPT="0", GIT_EDITOR="true")


def git(*a, **kw):
    return subprocess.run(["git", "-C", CW, "-c", "core.quotepath=false"] + list(a), capture_output=True, env=ENV, timeout=120, **kw)


def sync():
    if "--no-fetch" not in sys.argv:
        r = git("fetch", "origin", "claude/terra-prep-becker")
        print("fetch", "ok" if r.returncode == 0 else "failed: " + r.stderr.decode("utf-8", "replace")[:200])
    os.makedirs(SRC, exist_ok=True)
    for path, name in FILES:
        r = git("show", "%s:%s%s" % (REF, BASE, path))
        if r.returncode != 0:
            print("skip", name)
            continue
        out = os.path.join(SRC, name)
        old = open(out, "rb").read() if os.path.exists(out) else None
        if old != r.stdout:
            open(out, "wb").write(r.stdout)
            print("sync", name, len(r.stdout))
        else:
            print("same", name)


KEEP = ("id", "area", "format", "difficulty", "est_minutes", "testable_from", "law_asof", "law_note", "cite", "blueprint",
        "params", "vary", "guards", "derived")


def build():
    src = json.load(open(os.path.join(SRC, "tbs_reg.json"), encoding="utf-8"))
    items = []
    for t in src["items"]:
        o = {k: t[k] for k in KEEP}
        tp = t["template"]
        for k in ("title", "scenario", "task", "exhibits"):
            o[k] = tp[k]
        cells = []
        for c, r in zip(tp["cells"], t["cells"]):
            c = dict(c)
            c["points"] = r.get("points", 1)
            if c["kind"] == "dropdown":
                c["opts0"] = r["options"]  # shuffled order of the original (base numbers)
            cells.append(c)
        o["cells"] = cells
        items.append(o)
    meta = {"schema": src["meta"]["schema"], "count": len(items), "law_asof": src["meta"]["law_asof"]}
    out = os.path.join(ROOT, "data", "tbs_reg.js")
    body = "/* generated by tools/build_tbs.py from tools/src/TBS/tbs_reg.json - do not edit */\nwindow.TBS_DATA=" + \
        json.dumps({"meta": meta, "items": items}, ensure_ascii=False, separators=(",", ":")) + ";\n"
    open(out, "w", encoding="utf-8").write(body)
    print("wrote data/tbs_reg.js", len(body), "bytes,", len(items), "items")


if __name__ == "__main__":
    sync()
    build()
