# -*- coding: utf-8 -*-
"""Builds data/cards_reg.js (REG concept cards) for learn.html.

  py tools/sync_src.py     copies cards_reg.json into tools/src/REG
  py tools/build_reg.py    builds the Area data files (topic -> unit numbers come from them)
  py tools/build_cards.py  this script

Reads    tools/src/REG/cards_reg.json  and  data/reg_area*.js  (TREE, to link each card topic to its practice unit)
Writes   data/cards_reg.js             window.CARDS
         sw.js                         precache list and version are refreshed (the new files must be cached for offline use)
Idempotent. A card whose topic has no shipped practice unit is kept, without a practice link, and reported.
"""
import json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
try: sys.stdout.reconfigure(encoding="utf-8")
except Exception: pass
import reg_common as C

SRC = os.path.join(C.DEFAULT_SRC, "cards_reg.json")
DATA = os.path.join(C.ROOT, "data")
src = json.load(open(SRC, encoding="utf-8"))

# topic -> (subject key, unit no) from the built Area files
units, bank_ids = {}, set()
for ar in C.AREAS:
    key = C.SUBJECTS[ar][0]
    p = os.path.join(DATA, key + ".js")
    if not os.path.exists(p):
        continue
    t = open(p, encoding="utf-8").read()
    tree = json.loads(re.search(r"window\.TREE=(.*?);\nwindow\.QBANK=", t, re.S).group(1))
    qb = json.loads(re.search(r"window\.QBANK=(.*?);\nwindow\.PAIRS=", t, re.S).group(1))
    for n in tree["nodes"]:
        units[(ar, n["title"])] = (key, n["no"])
    for lst in qb.values():
        for q in lst:
            bank_ids.add(q["i"])

order = {a: i for i, a in enumerate(C.AREAS)}
cards, report = [], []
for c in sorted(src["cards"], key=lambda x: (order[x["area"]], x["group"], x["id"])):
    sk, nd = units.get((c["area"], c["topic"]), ("", 0))
    if not nd:
        report.append("no practice unit for %s (%s | %s)" % (c["id"], c["area"], c["topic"]))
    rel = [i for i in c.get("related_items", []) if i in bank_ids]
    ex = c["example"]
    cards.append({
        "id": c["id"], "area": c["area"], "group": c["group"], "topic": c["topic"], "title": c["title"],
        "rules": c["rule_lines"], "steps": c["steps"], "traps": c["traps"],
        "ex": {"q": ex["q"], "a": ex["a"], "work": ex["work"]},
        "cites": [{"l": x["label"], "u": x["url"]} for x in c["cites"]],
        "from": c.get("testable_from") or "", "asof": c.get("law_asof") or "",
        "sk": sk, "node": nd, "rel": rel,
    })

areas = [{"area": a, "title": C.AREA_TITLE[a], "key": C.SUBJECTS[a][0], "n": sum(1 for c in cards if c["area"] == a)} for a in C.AREAS]
out = os.path.join(DATA, "cards_reg.js")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Auto-generated by tools/build_cards.py — pipeline artifact. Do not hand-edit */\n")
    f.write("window.CARDS=" + json.dumps({"asof": src["meta"]["law_asof"], "areas": areas, "cards": cards}, ensure_ascii=False, separators=(",", ":")) + ";\n")

# offline cache: refresh the service worker file list and version so the new screen and data are cached
swp = os.path.join(C.ROOT, "sw.js")
if os.path.exists(swp):
    files = C.pwa_files()
    ver = C.pwa_version(files)
    sw = open(swp, encoding="utf-8").read()
    sw = re.sub(r"(/\* BEGIN PRECACHE[^\n]*\*/\n).*?(/\* END PRECACHE \*/)",
                lambda m: m.group(1) + 'var VERSION = "%s";\nvar FILES = %s;\n' % (ver, json.dumps(files, indent=1)) + m.group(2), sw, flags=re.S)
    open(swp, "w", encoding="utf-8", newline="\n").write(sw)
    report.append("sw.js version %s, %d files precached" % (ver, len(files)))

linked = sum(1 for c in cards if c["node"])
print("cards %d | practice link %d | related items found %d" % (len(cards), linked, sum(len(c["rel"]) for c in cards)))
print("\n".join(report))
