# -*- coding: utf-8 -*-
"""Build data/je_far.js (journal-entry drill data) from the source JSON files.

  py tools/build_je.py [SRC_DIR]

SRC_DIR defaults to ../wt-tp/jobs/terra-prep-becker/원천/FAR (the cloud-work worktree that holds je_*.json).
Reads je_coa.json (chart of accounts) and every other je_*.json (one file per topic; {topic, bp, templates[]}).
Writes  window.JE_DATA = {v, built, coa[], topics[], tpls[]}  — templates carry the generation rules; the browser
generates unlimited variants from them (js/je.js). Nothing is graded from stored answers: answers come from the formulas.
"""
import glob, json, os, re, sys, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEFAULT_SRC = os.path.normpath(os.path.join(ROOT, "..", "wt-tp", "jobs", "terra-prep-becker", "원천", "FAR"))
src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
out = os.path.join(ROOT, "data", "je_far.js")


def main():
    coa = json.load(open(os.path.join(src, "je_coa.json"), encoding="utf-8"))["coa"]
    ids = {a["id"] for a in coa}
    topics, tpls = [], []
    for fp in sorted(glob.glob(os.path.join(src, "je_*.json"))):
        if fp.endswith("je_coa.json"):
            continue
        d = json.load(open(fp, encoding="utf-8"))
        slug = re.sub(r"^je_|\.json$", "", os.path.basename(fp))
        tids = []
        for t in d["templates"]:
            for s in t["sets"]:
                for l in s["lines"]:
                    if l["a"] not in ids:
                        sys.exit("unknown account %s in %s" % (l["a"], t["id"]))
            t = dict(t)
            t["topic"] = slug
            tpls.append(t)
            tids.append(t["id"])
        topics.append({"id": slug, "name": d["topic"], "bp": d.get("bp", ""), "ids": tids})
    topics.sort(key=lambda x: x["name"])
    data = {"v": 1, "built": datetime.date.today().isoformat(), "coa": coa, "topics": topics, "tpls": tpls}
    body = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/build_je.py from je_*.json. Do not edit by hand. */\nwindow.JE_DATA=" + body + ";\n")
    print("wrote %s: %d templates, %d topics, %d accounts, %.0f KB" % (out, len(tpls), len(topics), len(coa), os.path.getsize(out) / 1024))


if __name__ == "__main__":
    main()
